BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TASK: "both"
DATASET_TYPE: "finger"
TRAIN:
  EPOCHS: 30
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    INFO:
      STATE: [1, 2, 3, 4] # 可以设置的 
      TYPE: [1, 2] # 1 - face, 2 - finger
  
    DATASET_TYPE: "finger" #['face', 'finger', 'both'] # 控制测试的数据集类型 
    FS: 60
    DATASET: THUSPO2
    DO_PREPROCESS: False              # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data2/lk/rppg-toolbox/QHU_SPO2"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data2/lk/rppg-toolbox/rppg_datasets/PreprocessedData/lk/test"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:1
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/finger_both
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: "/data2/lk/rppg-toolbox/runs/both_finger/THUSPO2_SizeW72_SizeH72_ClipLength128_DataTypeDiffNormalized_DataAugNone_LabelTypeDiffNormalized_Crop_faceTrue_BackendHC_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len32_Median_face_boxFalse/PreTrainedModels/THUSPO2_THUSPO2_THUSPO2_physnet_stan_finger_both_Epoch29.pth"