BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TASK: "both" 
DATASET_TYPE: "both" 
TRAIN:
  BATCH_SIZE:  10
  EPOCHS: 60

  LR: 9e-3
  MODEL_FILE_NAME: SUMS_SUMS_SUMS_multiphysnet_stan_face_spo2
  PLOT_LOSSES_AND_LR: True
  DATA:
    INFO:
      STATE: [1, 2, 3, 4]
      # STATE: [2]
      TYPE: [1, 2] # 1 - face, 2 - finger
    DATASET_TYPE: "both" #['face', 'finger', 'both'] 
    FS: 30
    DATASET: HMS 
    # DO_PREPROCESS: True      # if first time, should be true
    DO_PREPROCESS: False      # if first time, should be true
    DATA_FORMAT: NDCHW  #NDCHW   NCDHW
    DATA_PATH: "/data01/jz/mirror"  
    CACHED_PATH: "/data01/jz/train_HC"       # Processed dataset save path, need to be updated
    # CACHED_PATH: "/data01/jz/train_RF"       # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.7
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        # BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
VALID:
  DATA:
    INFO:
      STATE: [1, 2, 3, 4]
      # STATE: [2]
      TYPE: [1, 2] # 1 - face, 2 - finger
    DATASET_TYPE: "both" #['face', 'finger', 'both'] 
    FS: 30
    DATASET: HMS
    # DO_PREPROCESS: True      # if first time, should be true
    DO_PREPROCESS: False           # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data01/jz/mirror"      # Raw dataset path, need to be updated
    CACHED_PATH: "/data01/jz/train_HC"        # Processed dataset save path, need to be updated
    # CACHED_PATH: "/data01/jz/train_RF"       # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.7
    END: 0.9              
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        # BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    INFO:
      STATE: [1, 2, 3, 4] 
      # STATE: [2] 
      TYPE: [1, 2] # 1 - face, 2 - finger
    DATASET_TYPE: "both" #['face', 'finger', 'both'] 
    FS: 30
    DATASET: HMS
    # DO_PREPROCESS: True      # if first time, should be true
    DO_PREPROCESS: False        # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data01/jz/mirror"      # Raw dataset path, need to be updated
    CACHED_PATH: "/data01/jz/test_HC"        # Processed dataset save path, need to be updated  
    # CACHED_PATH: "/data01/jz/test_RF"       # Processed dataset save path, need to be updated  
    EXP_DATA_NAME: ""
    BEGIN: 0.9
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['DiffNormalized']
      DATA_AUG: ['None']    # 'None' or 'Motion' is supported, used if the data path points to an augmented dataset or requires augmentation
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        # BACKEND: 'RF'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY: 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: data01/jz/rppg_tool_HMS/runs2/face_rr
  # PATH: runs2/face_rr
MODEL:
  DROP_RATE: 0.2
  NAME: MultiPhysNet
  MultiPhysNet:
    FRAME_NUM:  128
INFERENCE:
  BATCH_SIZE: 16
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""

